### ISSUE TITLE
隠 is not found with [⻖心]

### ISSUE THREAD

**Issue by bhelyer** [itayperl/radical-lookup#1]
First of all, kantan seems amazing and is something I've thought about building but lacked the talent and/or effort to do, so hats off to you.

Not sure if this is the best venue for this, but I think 隠 should be findable with [⻖心]. I can't seem to make 隠 appear at all for that matter.

**Comment by itayperl** [comment]
Hey there, glad you liked it!

The reason your search didn't work is that KanTan looks up dictionary entries rather than individual kanji. 隠 on its own is not a dictionary entry, but 隠す is, so searching for "[⻖心]su" or "[⻖心]す" would work.

In many cases specifying a single radical per kanji is enough: "[⻖]su" and "[心]su" return 隠す as the first result, whereas "[心]ru" returns 怒る. As you can see, filtering by dictionary entries narrows down the search considerably.

Hope that helps :)
Itay
